services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Public:/var/www/html
    depends_on:
      - db
    command: sh -c "sleep 10 && php -S 0.0.0.0:80 -t /var/www/html"

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: lemsas
    ports:
      - "3307:3306"
